{
 "title": "Vmware Tanzu PCF Certificates",
 "description": "Dashboard to view all the certificate found on Vmware Tanzu Operation Manager",
 "tags": [
  "tanzu",
  "certificates"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "query": "vmware_tanzu_cert_exporter_cert_expires_in_seconds"
   }
  ]
 },
 "panels": [
  {
   "title": "Expiration <= 6m",
   "type": "singlestat",
   "description": "Certificates that will be expiring within 6m and needs immediate planning",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_tanzu_cert_exporter_cert_expires_in_seconds{env=~\"$Environment\"} <= 15724800) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Expiration > 6m & <= 1y",
   "type": "singlestat",
   "description": "Certificates that would expire within a year , but have  above 6m validity",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(15724800 < vmware_tanzu_cert_exporter_cert_expires_in_seconds{env=~\"$Environment\"} and vmware_tanzu_cert_exporter_cert_expires_in_seconds{env=~\"$Environment\"} <= 31536000) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Expiration > 1y",
   "type": "singlestat",
   "description": "Certificates that have validity for more than a year",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_tanzu_cert_exporter_cert_expires_in_seconds{env=~\"$Environment\"} > 31536000) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "singlestat",
   "description": "Total errors encountered by the cert exporter app, check the cert exporter app logs for more information",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(vmware_tanzu_cert_exporter_error_total{env=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Errors [1h]",
   "type": "graph",
   "description": "Time when the errors where encountered by the cert exporter app, check the cert exporter app logs for more information\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_tanzu_cert_exporter_error_total{env=~\"$Environment\"}[1h])",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Total OpsMan Certs",
   "type": "singlestat",
   "description": "Total certs managed by Opsman API on this lab \"$Environment\"",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vmware_tanzu_cert_exporter_cert_expires_in_seconds{location=\"ops_manager\", env=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Operation Manager Certificates",
   "type": "table",
   "description": "Certificates found or managed by OpsMan API",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "vmware_tanzu_cert_exporter_cert_expires_in_seconds{location=~\"ops_manager\", env=~\"$Environment\"}"
    }
   ]
  },
  {
   "title": "Total Credhub Certs",
   "type": "singlestat",
   "description": "Total certs managed by Opsman API on this lab \"$Environment\"",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vmware_tanzu_cert_exporter_cert_expires_in_seconds{location=\"credhub\", env=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Credhub Certificates",
   "type": "table",
   "description": "Certificates found on credhub by OpsMan API",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "vmware_tanzu_cert_exporter_cert_expires_in_seconds{location=~\"credhub\", env=~\"$Environment\"}"
    }
   ]
  }
 ]
}